health check check pt 2

diff --git a/.github/workflows/fly.yml b/.github/workflows/fly.yml
--- a/.github/workflows/fly.yml
+++ b/.github/workflows/fly.yml
@@ -7,13 +7,29 @@ on:
         - completed
 
 jobs:
-  deploy:
-    name: Deploy app
-    runs-on: ubuntu-20.04
-    concurrency: deploy-group    # optional: ensure only one action runs at a time
-    steps:
-      - uses: actions/checkout@v4
-      - uses: superfly/flyctl-actions/setup-flyctl@master
-      - run: flyctl deploy --remote-only
-        env:
-          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
+    deploy:
+      name: Deploy app
+      runs-on: ubuntu-20.04
+      concurrency:
+        group: deploy-group  # optional: ensure only one action runs at a time
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v2
+  
+        - name: Setup Flyctl
+          uses: superfly/flyctl-actions/setup-flyctl@master
+  
+        - name: Run health check
+          run: |
+            health_check_result=$(curl -s http://localhost:3000/health)
+  
+            if [ "$health_check_result" = "ok" ]; then
+              echo "Health check passed. Proceeding with deployment."
+            else
+              echo "Health check failed. Skipping deployment."
+              exit 1  
+            fi          
+        - name: Deploy
+          run: flyctl deploy --remote-only
+          env:
+            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
